### ISSUE TITLE
Kafka Start Message Event Connector: process instances created even after changing topic

### ISSUE THREAD

**Issue by ev-codes** [camunda/connectors#3148] opened 2024-08-22 12:00 UTC
__Describe the Bug__

Even after changing the Connector's Kafka topic and its BPMN's process ID, both old and new process definitions are instantiated after producing a message to the new topic.

__Steps to Reproduce__

1. Create a new BPMN file in Desktop Modeler with a Kafka Start Message Event Connector with topic S
2. Deploy the process (let's call it process A)
3. Edit the new BPMN by changing the process ID and by changing the topic to T
4. Deploy the process (process B). There should now be two separate process definitions (A and B) visible in Operate.
5. Produce a Kafka message on topic T
6. A new instance for both A and B is created
7. Produce a message on topic S
8. A new instance for both A and B is created

__Expected Behavior__

- After producing a message on topic T, we should only see one new instance created for process B.
- After producing a message on topic S, we should only see one new instance created for process A.

__Environment__

- OS: macOS 14.6.1
- Desktop Modeler version: 5.26.0
- Connectors Runtime version: 8.5.5 and 8.5.3

**Comment by ev-codes** [comment] 2024-08-23 13:27
I took a quick, timeboxed look at this issue today.

- I added some more details to the issue description
- Process definitions A and B:
    - have a different `processId`
    - have the same `tenantId` "<default"

**Comment by johnBgood** [comment] 2024-08-26 08:00
From @chillleader :

I think the issue here is that the message name remains the same if you change some connector properties. The message name seems to be auto-generated in the modeler. As a result, both process definitions are still active and waiting for a message with the same ID to be triggered.
If this theory is true, deleting a Kafka message start event and adding it again with the same properties should lead to a different message name and this issue should not be reproducible

I wouldn't say it's an issue in the Kafka connector. If the guess above is true, I think we should create a ticket in the [element-templates](https://github.com/bpmn-io/bpmn-js-element-templates) repo and discuss potential solutions with the [bpmn.io](http://bpmn.io/) team



[9:58](https://camunda.slack.com/archives/C0350959WG1/p1724659106233689?thread_ts=1724656959.896509&cid=C0350959WG1)
I wouldn't say it's an issue in the Kafka connector. If the guess above is true, I think we should create a ticket in the [element-templates](https://github.com/bpmn-io/bpmn-js-element-templates) repo and discuss potential solutions with the [bpmn.io](http://bpmn.io/) team

**Comment by johnBgood** [comment] 2024-08-27 15:36
Will close this ticket as I created https://github.com/bpmn-io/bpmn-js-element-templates/issues/119

**Closed by johnBgood** 2024-08-27 15:36 UTC
