### ISSUE TITLE
REST Connector: validation for URL not working in all cases

### ISSUE THREAD

**Issue by MaxTru** [camunda/connectors#1382] opened 2023-11-07 10:11 UTC
__Describe the Bug__

REST Connector: validation for URL not working in all cases

__Steps to Reproduce__

1. Use the REST POST Connector
2. Have the following FEEL statement for the URL: 
```
"https://api.github.com/repos/camunda/product-hub/issues/" +
  string(epicIssueNumber) +
  "/comments"
```
3. Deploy diagram => everything works
4. See that Linting gives an error: 
<img width="1236" alt="Bildschirmfoto 2023-11-07 um 11 10 38" src="https://github.com/camunda/connectors/assets/42800119/7056e46e-311c-4196-8f82-7e5163ae9e91">

__Expected Behavior__

Linting only highlights actual errors

__Environment__

SaaS as of 07.11. on a 8.3.x cluster

**Comment by sbuettner** [comment] 2023-11-13 13:55
@MaxTru The multi-line input breaks the input validation check as we only test non-FEEL input. Its therefore an outcome of the missing multi-line support in the modeler FEEL syntax validation. 

cc @nikku

**Comment by MaxTru** [comment] 2023-11-17 09:03
Hi Simon,
I think there was an update on this, but I forgot :-) Can you please recommend what way I should best format this (I want to get rid of the errors in our diagram). Currently I have:
```
"https://api.github.com/repos/camunda/product-hub/issues/" +
  string(epicIssueNumber) +
  "/comments"
```

**Comment by sbuettner** [comment] 2023-11-17 09:09
Hey @MaxTru as this was merged https://github.com/camunda/feel-scala/issues/701 we have to wait until zeebe is using the new FEEL engine. Hopefully in the next release in December. This will unblock this issue. For now you will have to either use the rest connector or convert the issue number to a string in a previous script task.

**Comment by CharlieBytesX** [comment] 2024-09-30 19:15
Hi, what's the proper way to interpolate strings with process variables?

**Comment by CharlieBytesX** [comment] 2024-09-30 19:15
Or append

**Comment by ev-codes** [comment] 2024-10-01 07:36
Hi @CharlieBytesX !

Your FEEL expression looks ok to me.

Here's some troubleshooting steps:
- Make sure the dynamic FEEL expression button (fx) next to the URL field is enabled. When enabled, the button should turn blue and an equals sign should appear next to the text field (see screenshot).
- Make sure the `employee_cr_id` process variable is not null. If a null value is expected, you could try an expression like: `"YOUR_URL" + (if employee_cr_id then string(employee_cr_id) else "")`

![Screenshot 2024-10-01 at 9 28 08 AM](https://github.com/user-attachments/assets/c705920f-b397-45de-a64d-7980c688175c)

**Comment by ev-codes** [comment] 2024-10-01 08:47
I'm closing the issue because:
- I can no longer reproduce the bug
- I don't think @CharlieBytesX 's question is related to the original bug in this issue

We can re-open this issue later if needed 😄

**Closed by ev-codes** 2024-10-01 08:47 UTC
Labels: kind:bug
