### ISSUE TITLE
Secrets not resolved in Kafka Connector config

### ISSUE THREAD

**Issue by eslateBP3** [camunda/connectors#972] opened 2023-08-01 00:35 UTC
__Describe the Bug__

For an inbound start event Kafka Connector, setting **Bootstrap servers** to a secret `secrets.KAFKA_SERVER` results in the secret not resolving and the initialization of the Connector failing.

__Steps to Reproduce__

1. Use Connectors version 0.21.4 (for Runtime and Kafka Connector)
2. Use Zeebe / Operate version 8.2.4
3. Set up a secret as an environment variable.
4. Specify the environment variable in a Kafka Consumer start event under Bootstrap servers.
5. Deploy BPMN.
6. Start Connectors and watch log - connector config will log the _secrets.ENV-VAR-NAME_ rather than value. Connector will fail to initialize:
`i.c.c.k.inbound.KafkaConnectorConsumer   : Failed to initialize connector: Failed to construct kafka consumer`

1. Downgrade Connectors versions to 0.21.3 and it will resolve the secret and log the value rather than name.

__Expected Behavior__

Connector secrets should resolve successfully.

__Environment__

- OS: MacOS / Linux
- Library version: 0.21.4 (also reproduces with 0.22.0-SNAPSHOT)
- Camunda version: 8.2.4 Cloud

**Comment by chillleader** [comment] 2023-08-01 15:58
Hey @eslateBP3, thanks for reporting! I can confirm that the issue is reproducible.

There seems to be an issue with the secrets resolution for inbound connectors in general in this version. The root cause is the new secret replacement logic we introduced in `0.21.0` that made the `@Secret` annotation not mandatory. Connectors that have adopted this change already are affected.

Although the change itself was introduced in `0.21.0`, our OOTB Kafka inbound connector only got rid of `@Secret` annotations by `0.21.4` -- that's why the issue has only become apparent now.

This will be fixed in this PR: https://github.com/camunda/connectors/pull/982. We will then discuss with the team whether we will do a patch release or just fix it in the next minor version 0.22.0 (coming next week, so this option is more likely).

**Comment by chillleader** [comment] 2023-08-02 11:46
This should be fixed in the latest snapshot

**Comment by chillleader** [comment] 2023-08-03 13:44
The fix was released as part of `0.22.0-alpha2`. It will be part of the stable`0.22.0` release next Tuesday.

**Closed by chillleader** 2023-08-03 13:44 UTC
Labels: kind:bug
