### ISSUE TITLE
Webhook is not being activated when modelled inside an embedded subprocess 

### ISSUE THREAD

**Issue by CatalinaMoisuc** [camunda/connectors#1050] opened 2023-08-17 11:24 UTC
Issue originally posted by @McAlm in Web Modeler repo [here](https://github.com/camunda/web-modeler/issues/5760). 

### Bug description

When a Webhook connector is configured WITHIN an embedded subprocess the webhook will not be activated after deployment.

### Steps to reproduce
1. Create a model with an embedded subprocess
2. model a start event, an intermediate event and an end event into the subprocess.
3. configure the intermediate event as webhook
4. deploy the model
5. look at the webhook tab

### Expected Behavior

Naja, the webhook should be activated...

### Environment

SaaS 8.3.0-alpha4 and 8.2.11

---------------------------------------------------------------------------------------------

### Acceptance Criteria

#
### Definition of Ready - Checklist

- [ ] the bug has been reproduced by the assignee; otherwise, the issue is closed with a comment
- [ ] the issue has a meaningful title, description, and testable acceptance criteria
- [ ] necessary screenshots, screen recordings, or files are attached to the bug report
- [ ] environment details are checked and complete
- [ ] for UI changes required to solve the bug
    - [ ] design input has been collected by the assignee

**Comment by igpetrov** [comment] 2023-08-17 12:25
Taking over from here: https://camunda.slack.com/archives/C034N0E5YCX/p1692275009637549?thread_ts=1692262134.556679&cid=C034N0E5YCX

**Comment by igpetrov** [comment] 2023-08-17 12:34
Duplicate of https://github.com/camunda/connectors/issues/782.

**Closed by igpetrov** 2023-08-17 12:34 UTC
Labels: kind:bug
