### ISSUE TITLE
Properties names are reserved and can not be used as output variable names

### ISSUE THREAD

**Issue by christian-konrad** [camunda/connectors#49] opened 2022-09-07 17:43 UTC
__Describe the Bug__

When using the HTTP Connector, I can map response content to output variables using a FEEL destructuring assignment expression. But when I try to give a result variable a name that is already used in a property of the Connector (such as `url` or `body`, the variable is not available in the global context. In operate, you can still see the value assigned to that variable in the local context, but you can't see it globally or in subsequent tasks. The user-defined variable names clashes with the internal ones of the connector template. 

(I am not sure if this is the right repo, or if this should belong somewhere else)

__Expected Behavior__

Give the connector properties names a scope, such as `connector:http:url`, to avoid clashes with user-defined variable names. 

__Environment__

- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]
- Camunda Cloud Environment: [e.g. staging / prod, cluster]

**Comment by sbuettner** [comment] 2024-08-19 12:43
Not reproducible. Closing it for now.

**Closed by sbuettner** 2024-08-19 12:43 UTC
Labels: kind:bug, scope:rest

**Comment by sbuettner** [comment] 2024-08-19 12:59
@aleksander-dytko can you take a look at this one with your team? Looks like a zeebe issue and not like something we can manage from within the Connectors Runtime.
