### ISSUE TITLE
Polling Connector Is Not Functioning Properly

### ISSUE THREAD

**Issue by slolatte** [camunda/connectors#2751] opened 2024-06-13 14:32 UTC
__Describe the Bug__

When using the polling connector within a process, I am getting UI errors in the Console and as well the connector will not complete in Operate. However according to the polling tab the connector is correctly polling and active.

__Steps to Reproduce__

I used the attached diagram and started the process instance with variable: {"bodyStatus":"success"}. 

The GITHUB_TOKEN I posted in Keeper (Shared Connectors -> QA GitHub Token)

[Retrieve Test Run Completed Results.bpmn.zip](https://github.com/user-attachments/files/15822012/Retrieve.Test.Run.Completed.Results.bpmn.zip)

<img width="1493" alt="Screenshot 2024-06-13 at 16 24 07" src="https://github.com/camunda/connectors/assets/132344616/d86fa87e-8d1c-46e5-a063-8324e6480b9c">

__Expected Behavior__

Errors should not appear in the Console and the polling connector should complete in Operate. 

__Environment__

- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]
- Camunda version: [e.g. 8.0.4 (self-managed)]

**Comment by markfarkas-camunda** [comment] 2024-10-11 12:00
Cannot reproduce the issue not even with the linked bpmn file. Also from the screenshot it looks like we got an html page as a response from connectors which is likely an error response and indicates that the connectors component was not healthy. Closing the issue for now.

**Closed by markfarkas-camunda** 2024-10-11 12:00 UTC
Labels: kind:bug
